package com.iqra.restaurantapp.entity;
// Generated Jun 4, 2021 10:34:20 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", schema = "public")
public class Customer implements java.io.Serializable {

	private long customerId;
	private String name;
	

	public Customer() {
	}

	public Customer(long customerId) {
		this.customerId = customerId;
	}

	public Customer(long customerId, String name) {
		this.customerId = customerId;
		this.name = name;
		
	}

	@Id
	@SequenceGenerator(allocationSize = 1, initialValue = 1, sequenceName = "public.customer_seq", name = "customer_seq")
	@GeneratedValue(generator = "customer_seq", strategy = GenerationType.SEQUENCE)
	@Column(name = "customer_id", unique = true, nullable = false)
	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
}
