package com.iqra.restaurantapp.entity;
// Generated Jun 4, 2021 10:34:20 AM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", schema = "public")
public class Item implements java.io.Serializable {

	private int itemId;
	private String name;
	private BigDecimal price;
	

	public Item() {
	}

	public Item(int itemId) {
		this.itemId = itemId;
	}

	public Item(int itemId, String name, BigDecimal price) {
		this.itemId = itemId;
		this.name = name;
		this.price = price;
		
	}

	@Id
	@SequenceGenerator(allocationSize = 1, initialValue = 1, sequenceName = "public.item_seq", name = "item_seq")
	@GeneratedValue(generator = "item_seq", strategy = GenerationType.SEQUENCE)
	@Column(name = "item_id", unique = true, nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", precision = 18)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	
}
