package com.iqra.restaurantapp.entity;
// Generated Jun 4, 2021 10:34:20 AM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", schema = "public")
public class Order implements java.io.Serializable {

	private long orderId;
	private Customer customer;
	private String orderNo;
	private String pmethod;
	private BigDecimal gtotal;
	private Set<OrderItems> orderItemDetailses = new HashSet<OrderItems>(0);

	public Order() {
	}

	public Order(long orderId) {
		this.orderId = orderId;
	}

	public Order(long orderId, Customer customer, String orderNo, String pmethod, BigDecimal gtotal,
			Set<OrderItems> orderItemsDetails) {
		this.orderId = orderId;
		this.customer = customer;
		this.orderNo = orderNo;
		this.pmethod = pmethod;
		this.gtotal = gtotal;
		this.orderItemDetailses = orderItemsDetails;
		
	}

	@Id
	@SequenceGenerator(allocationSize = 1, initialValue = 1, sequenceName = "public.order_seq", name = "order_seq")
	@GeneratedValue(generator = "order_seq", strategy = GenerationType.SEQUENCE)
	@Column(name = "order_id", unique = true, nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "order_no", length = 50)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "pmethod", length = 50)
	public String getPmethod() {
		return this.pmethod;
	}

	public void setPmethod(String pmethod) {
		this.pmethod = pmethod;
	}

	@Column(name = "gtotal", precision = 18)
	public BigDecimal getGtotal() {
		return this.gtotal;
	}

	public void setGtotal(BigDecimal gtotal) {
		this.gtotal = gtotal;
	}
	
	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order",cascade=CascadeType.ALL)
	public Set<OrderItems> getOrderItemDetailses() {
		return orderItemDetailses;
	}

	public void setOrderItemDetailses(Set<OrderItems> orderItemDetailses) {
		this.orderItemDetailses = orderItemDetailses;
	}

	
	


}
