package com.iqra.restaurantapp.entity;
// Generated Jun 4, 2021 10:34:20 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * OrderItems generated by hbm2java
 */
@Entity
@Table(name = "order_items", schema = "public")
public class OrderItems implements java.io.Serializable {

	private long orderItemId;
	private Item item;
	private Order order;
	private Integer quantity;

	public OrderItems() {
	}

	public OrderItems(long orderItemId) {
		this.orderItemId = orderItemId;
	}

	public OrderItems(long orderItemId, Item item, Order order, Integer quantity) {
		this.orderItemId = orderItemId;
		this.item = item;
		this.order = order;
		this.quantity = quantity;
	}

	@Id
	@SequenceGenerator(allocationSize = 1, initialValue = 1, sequenceName = "public.order_items_seq", name = "order_items_seq")
	@GeneratedValue(generator = "order_items_seq", strategy = GenerationType.SEQUENCE)
	@Column(name = "order_item_id", unique = true, nullable = false)
	public long getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(long orderItemId) {
		this.orderItemId = orderItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
